SELECT T.ID,
	T.RANK,
	T.NAME,
	T.STATUS,
	T.POSITION,
	T.RANKVALUE
FROM (
	SELECT DISTINCT TD.ID,
		TD.RANK,
		TD.NAME,
		TD.STATUS,
		TD.POSITION,
		TR.PATH,
		R.RANKVALUE
	FROM
		(SELECT *
			FROM TAXONOMY_REGISTRY
			WHERE PATH <@
					(SELECT PATH
						FROM TAXONOMY_REGISTRY
						WHERE TAXON_DEFINITION_ID = :taxonId
							AND CLASSIFICATION_ID = :classificationId)) TR
	LEFT JOIN TAXONOMY_RANK R ON TR.RANK = R.NAME
	LEFT JOIN ACCEPTED_SYNONYM A ON TR.TAXON_DEFINITION_ID = A.ACCEPTED_ID
	LEFT JOIN TAXONOMY_DEFINITION TD ON TD.ID = TR.TAXON_DEFINITION_ID
	OR TD.ID = A.SYNONYM_ID
) T
WHERE STATUS IN (:status) AND POSITION IN (:position) AND RANK IN (:rank)
ORDER BY CAST(STRING_TO_ARRAY(LTREE2TEXT(PATH),'.') AS INT[]), STATUS, NAME
